apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: example

commonLabels:
  app: actions

resources:
  - namespace.yaml
  - runner.yaml
  - pv.yaml

configMapGenerator:
- name: repository-variables
  envs: [.env]
  behavior: create

vars:
- name: REPOSITORY
  objref:
    kind: ConfigMap
    name: repository-variables
    apiVersion: v1
  fieldref:
    fieldpath: data.REPOSITORY

configurations:
  - env-var-transformer.yaml

