---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  annotations:
    volume.beta.kubernetes.io/storage-class: "fast"
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /tmp/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - lima-rancher-desktop
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim
  labels:
    app: pv
  annotations:
    "volume.beta.kubernetes.io/storage-class": "fast"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
