source <(kubectl completion zsh)

PROMPT='$(kube_ps1)'$PROMPT
alias k=kubectl

if [[ "$SYNC_LOCALHOST_KUBECONFIG" = "true" ]] && [[ ! -d $HOME/.kube ]]; then
  mkdir -p $HOME/.kube
  cp -r $HOME/.kube-localhost/* $HOME/.kube
  chown -R $(id -u) $HOME/.kube
  sed -i -e "s/localhost/host.docker.internal/g" $HOME/.kube/config
  sed -i -e "s/127.0.0.1/host.docker.internal/g" $HOME/.kube/config
fi
